### ISSUE TITLE
pca calculation in ./analysis/analysis_figures.R

### ISSUE THREAD

**Issue by cscheeder** [Swarchal/TCCS_paper#1]
in line 16 of ./analysis/analysis_figures.R the _get_featuredata()_ function call seems not to work.
I used either _get_featuredata()_ alone or _x[, get_feature_cols(x, ...)]_ and it seems to work

**Comment by cscheeder** [comment]
figured out that loading the packages manually should be avoided

**Comment by Swarchal** [comment]
Is this sorted, I can't quite figure out what happened?

**Comment by cscheeder** [comment]
Yes, works fine! It was my own mistake... I tried to run ./analysis/analysis_figures.R directly and installed the required packages manually instead of using your load_packages.R script. After using load_packages.R  to install the dependencies everything worked! Sorry for the confusion.
